# Generated by Django 4.2 on 2023-04-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150)),
                ('disabilityType', models.CharField(max_length=150)),
                ('schemeName', models.TextField(max_length=100000)),
                ('benefitCriteria', models.CharField(max_length=150)),
                ('typesOfBenefit', models.CharField(max_length=150)),
            ],
        ),
    ]
