# Generated by Django 4.2 on 2023-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_remove_counts_pagevisit_counts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(default=None)),
                ('username', models.CharField(default=None, max_length=150)),
                ('userage', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Counts',
            new_name='VisitCounts',
        ),
        migrations.RenameField(
            model_name='visitcounts',
            old_name='user',
            new_name='user_ip',
        ),
    ]
